In [ ]:
# For Google Colaboratory
import sys, os
if 'google.colab' in sys.modules:
    # mount google drive
    from google.colab import drive
    drive.mount('/content/gdrive')
    path_to_file = '/content/gdrive/My Drive/Data Science Files/NUS_courses/Applied_Machine_Learning/Applied_ML/Practical' # Please adjust the path accordingly
    os.chdir(path_to_file)
    !pwd



Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/My Drive/Data Science Files/NUS_courses/Applied_Machine_Learning/Applied_ML/Practical


In [ ]:
import pandas as pd
df = pd.read_csv('bank.csv')
df

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

## 1. Python Basics

### 1.1 Syntax

In [ ]:
2 + 2

4

In [ ]:
x = 5
y = 2
x * y

10

In [ ]:
x ** y

25

In [ ]:
print('Hello, world!')

Hello, world!



### 1.2 Data Types

#### 1.2.1 Booleans

'True' and 'False' have special meaning in Python.

In [ ]:
a = True
b = False

In [ ]:
a == True

True

In [ ]:
b == True

False

In [ ]:
a or b

True

In [ ]:
a and b

False

#### 1.2.2 Numbers: integers and floats

Numbers are pretty straightforward, especially in Python 3.

In [ ]:
1 + 2

3

In [ ]:
1.0 + 2.0

3.0

In [ ]:
1 / 2

0.5

In [ ]:
1.0 / 2.0

0.5

In [ ]:
type(1)

int

In [ ]:
type(1/2)

float

In [ ]:
a=5.3
type(a)

float

In [ ]:
a=int(a)
print(a)
print(type(a))

5
<class 'int'>


The next four data types -- strings, lists, tuples, arrays -- are all sequences.

#### 1.2.3 Strings

Strings are sequences of characters.

In [ ]:
s = 'Hello, world'

In [ ]:
type(s)

str

In [ ]:
s[0:4]

'Hell'

In [ ]:
s + '!'

'Hello, world!'

In [ ]:
s

'Hello, world!'

In [ ]:
s = s + '!'

In [ ]:
s

'Hello, world!'

#### 1.2.4 Lists

Lists are _mutable_ sequences of anything.

In [ ]:
l = [0, 1, 1, 2, 3, 5, 8]

In [ ]:
l[0:3]

[0, 1, 1]

In [ ]:
m = [5, 2, 'a', 'xxx', True, [0, 1]]

In [ ]:
m[4]

True

In [ ]:
m[4] = False

In [ ]:
m[4:]

[False, [0, 1]]

#### 1.2.5 Tuples

Tuples are immutable sequences of anything (similar to lists except you can't change them).

In [ ]:
n = (3, 5, 6)

In [ ]:
n[0]

3

In [ ]:
n[0] = 2

TypeError: ignored

#### 1.2.6 Arrays (numpy array)

A numpy array is a grid of values, all of the same type.

In [ ]:
# Import modules to use
import math
import numpy as np

In [ ]:
mylist = [0, 2, 4]
np.array(mylist)

array([0, 2, 4])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.random.rand()

0.6360278953882786

In [ ]:
np.random.rand(5)

array([0.79254455, 0.82970199, 0.08554152, 0.83740733, 0.13137227])

#### 1.2.7 Sets

Sets are unordered collections of unique objects.

In [ ]:
s1 = {'a', 'b', 'c'}
s2 = {'a', 'd', 'e'}

In [ ]:
# AND
s1 & s2

{'a'}

In [ ]:
# OR
s1 | s2

{'a', 'b', 'c', 'd', 'e'}

In [ ]:
l = [0, 1, 1, 2, 3, 5, 8]
s3 = set(l)
s3

{0, 1, 2, 3, 5, 8}

In [ ]:
m = [5, 2, 'a', 'xxx', True, [0, 1]]
s4 = set(m[0:2])
s4

{2, 5}

In [ ]:
s3 & s4

{2, 5}

In [ ]:
s3 | s4

{0, 1, 2, 3, 5, 8}

In [ ]:
s3 - s4

{0, 1, 3, 8}

#### 1.2.8 Dictionaries

Dictionaries or 'dicts' are hash tables, where a key points to a value.

In [ ]:
d = {'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [ ]:
d

{'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [ ]:
d['name']

'John Doe'

In [ ]:
d['zip'] = 92039

In [ ]:
d

{'name': 'John Doe', 'age': 27, 'dob': '7/20/1989', 'zip': 92039}

### 1.3 Loops and Control Structures

#### 1.3.1 Boolean and comparison operations

In [ ]:
x = 5
(x < 6) and (x > 4)

True

In [ ]:
x != 4

True

In [ ]:
5 in [3, 4, 5]

True

In [ ]:
'ell' in 'Hello'

True

In [ ]:
len('Hello') >= 5

True

#### 1.3.2 if tests

In [ ]:
x = -15

if x==0:
    print(x,'is zero')
elif x > 0:
    print(x, 'is positive')
else:
    print(x, 'is negative')

-15 is negative


#### 1.3.3 while loops

In [ ]:
i = 0
while (i < 5):
    print(i)
    i += 1

0
1
2
3
4


In [ ]:
i

5

#### 1.3.4 for loops

In [ ]:
for x in [0, 1, 2, 3, 4]:
    print(x**2)

0
1
4
9
16


## 2. Pandas

Pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series.

In [ ]:
import pandas as pd
import numpy as np


### 2.1 Series
A list of data with the same data type.

In [ ]:
# a list of strings
my_list = ['cubs', 'pirates', 'giants', 'yankees', 'donkeys']
my_list

['cubs', 'pirates', 'giants', 'yankees', 'donkeys']

In [ ]:
# pandas Series from list
series_from_list = pd.Series(my_list)
series_from_list

0       cubs
1    pirates
2     giants
3    yankees
4    donkeys
dtype: object

In [ ]:
# indexing a Series is similar to lists and arrays
series_from_list[3]

'yankees'

In [ ]:
# a numpy array
my_array = np.random.rand(5)
my_array

array([0.31541156, 0.52903641, 0.35138555, 0.93513212, 0.41532709])

In [ ]:
# pandas Series from array
series_from_array = pd.Series(my_array)
series_from_array

0    0.315412
1    0.529036
2    0.351386
3    0.935132
4    0.415327
dtype: float64

In [ ]:
# indexing supports lists
series_from_array[[1, 3]]

1    0.529036
3    0.935132
dtype: float64

In [ ]:
# indexing supports slices
series_from_array[3:]

3    0.935132
4    0.415327
dtype: float64

### 2.2 DataFrame

#### 2.2.1 2D array to DataFrame

In [ ]:
# create a 2D numpy array
my_2d_array = np.random.randn(5,5)
my_2d_array

array([[-0.80446177,  0.67979639, -0.14640363,  1.48446441,  0.0799853 ],
       [ 1.4671996 , -0.61451719, -0.61125319,  1.90777396, -0.01255177],
       [-2.00022603, -0.89138626, -1.74690543,  0.90819745, -0.63076264],
       [-0.26805659,  0.75363572,  0.32365515,  1.2053862 ,  0.74620045],
       [ 0.46136114, -1.40768959,  0.96527119,  0.12402362,  0.49657968]])

In [ ]:
# make a DataFrame from the 2D numpy array
pd.DataFrame(my_2d_array)

0         1         2         3         4
0 -0.804462  0.679796 -0.146404  1.484464  0.079985
1  1.467200 -0.614517 -0.611253  1.907774 -0.012552
2 -2.000226 -0.891386 -1.746905  0.908197 -0.630763
3 -0.268057  0.753636  0.323655  1.205386  0.746200
4  0.461361 -1.407690  0.965271  0.124024  0.496580

In [ ]:
# we can set the index and column labels when we create the DataFrame
# note that we can combine positional arguments (data) and keyword arguments
# (index, columns) as long as positional arguments come first
df_from_2d_array = pd.DataFrame(
    my_2d_array,
    index=['row1', 'row2', 'row3', 'row4', 'row5'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5'])
df_from_2d_array

col1      col2      col3      col4      col5
row1 -0.804462  0.679796 -0.146404  1.484464  0.079985
row2  1.467200 -0.614517 -0.611253  1.907774 -0.012552
row3 -2.000226 -0.891386 -1.746905  0.908197 -0.630763
row4 -0.268057  0.753636  0.323655  1.205386  0.746200
row5  0.461361 -1.407690  0.965271  0.124024  0.496580

#### 2.2.2 Converting multiple Series to a DataFrame

In [ ]:
# method 1: pass list/Series as value of dictionary
y = pd.DataFrame({'a': series_from_list, 'b': series_from_array})
y

a         b
0     cubs  0.315412
1  pirates  0.529036
2   giants  0.351386
3  yankees  0.935132
4  donkeys  0.415327

In [ ]:
# importing the data as columns gives us the correct dtypes
y.dtypes

a     object
b    float64
dtype: object

In [ ]:
# method 2: use pd.concat to combine series in column orientation
df = pd.concat([series_from_list, series_from_array], axis=1)
df

0         1
0     cubs  0.315412
1  pirates  0.529036
2   giants  0.351386
3  yankees  0.935132
4  donkeys  0.415327

In [ ]:
# again, importing the data as columns gives us the correct dtypes
df.dtypes

0     object
1    float64
dtype: object


### 2.3 index, columns

In [ ]:
# numeric indexes
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# numeric column names
df.columns

RangeIndex(start=0, stop=2, step=1)

In [ ]:
# rename columns and indexes - method 1
# set the index and column names to an existing DataFrame
df.index = ['a', 'b', 'c', 'd', 'e']
df.columns = ['team', 'random']
df

team    random
a     cubs  0.315412
b  pirates  0.529036
c   giants  0.351386
d  yankees  0.935132
e  donkeys  0.415327

In [ ]:
# label (object) indexes
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
# label (object) column names
df.columns

Index(['team', 'random'], dtype='object')

In [ ]:
# add a new column to the end of a DataFrame
df['integers'] = [2, 3, 5, 8, 13]
df

team    random  integers
a     cubs  0.315412         2
b  pirates  0.529036         3
c   giants  0.351386         5
d  yankees  0.935132         8
e  donkeys  0.415327        13

In [ ]:
# add a new column at a specific position
df.insert(0, 'integers2', [2, 3, 5, 8, 13])
df

integers2     team    random  integers
a          2     cubs  0.315412         2
b          3  pirates  0.529036         3
c          5   giants  0.351386         5
d          8  yankees  0.935132         8
e         13  donkeys  0.415327        13

In [ ]:
# delete a column
df.drop('integers2', axis=1, inplace=True)
df

team    random  integers
a     cubs  0.315412         2
b  pirates  0.529036         3
c   giants  0.351386         5
d  yankees  0.935132         8
e  donkeys  0.415327        13

In [ ]:
# rename columns - method 2
# using dictionary mapping old names to new names
df.rename(columns={'integers': 'fibonacci'}, inplace=True)
df

team    random  fibonacci
a     cubs  0.315412          2
b  pirates  0.529036          3
c   giants  0.351386          5
d  yankees  0.935132          8
e  donkeys  0.415327         13

In [ ]:
# reorder the columns by passing a list of columns in the desired order
df[['fibonacci', 'team', 'random']]

fibonacci     team    random
a          2     cubs  0.315412
b          3  pirates  0.529036
c          5   giants  0.351386
d          8  yankees  0.935132
e         13  donkeys  0.415327

### 2.4 dtypes, info, describe

In [ ]:
# gives the datatype of each column
df.dtypes

team          object
random       float64
fibonacci      int64
dtype: object

In [ ]:
# shape (dimensions) of dataframe
df.shape

(5, 3)

In [ ]:
# information about index and columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   team       5 non-null      object 
 1   random     5 non-null      float64
 2   fibonacci  5 non-null      int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes


In [ ]:
# basic statistics
df.describe()

random  fibonacci
count  5.000000   5.000000
mean   0.509259   6.200000
std    0.251537   4.438468
min    0.315412   2.000000
25%    0.351386   3.000000
50%    0.415327   5.000000
75%    0.529036   8.000000
max    0.935132  13.000000

<a id="readcsv"></a>

### 2.5 read_csv

In [ ]:
# read_csv with defaults
# by default column headers are the first row and row indexes are integers starting from zero
df_t = pd.read_csv('bank.csv')

In [ ]:
df_t.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [ ]:
# show the data type of each column
df_t.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
deposit      object
dtype: object

In [ ]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [ ]:
df_t.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

<a id="headtail"></a>

### 2.6 head, tail

In [ ]:
# add a number to change the number of rows printed
df_t.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [ ]:
# tail works the same way
df_t.tail(3)

age         job  marital  education default  balance housing loan  \
11159   32  technician   single  secondary      no       29      no   no   
11160   43  technician  married  secondary      no        0      no  yes   
11161   34  technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
11159      no  
11160      no  
11161      no

In [ ]:
# if we view the whole dataframe, only the first 30 and last 30 rows are shown
df_t

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]


### 2.7 Indexing with bracket/dot notation, loc, iloc

Pandas has three indexing methods:

* `[ ]` and `.` work on labels of columns
* `.loc` works on labels of indexes and columns
* `.iloc` works on the positions of indexes and columns (so it only takes integers)

In [ ]:
df

team    random  fibonacci
a     cubs  0.315412          2
b  pirates  0.529036          3
c   giants  0.351386          5
d  yankees  0.935132          8
e  donkeys  0.415327         13

#### 2.7.1 brackets only -- column by header

In [ ]:
# to get a column (Series), use the column header (don't need .loc, .iloc, or .ix)
df['team']

a       cubs
b    pirates
c     giants
d    yankees
e    donkeys
Name: team, dtype: object

In [ ]:
# for multiple columns, put a list inside the brackets (so two sets of brackets)
df[['team', 'random']]

team    random
a     cubs  0.315412
b  pirates  0.529036
c   giants  0.351386
d  yankees  0.935132
e  donkeys  0.415327

#### 2.7.2 dot-notation

In [ ]:
# if the column name has only alpha-numerics (including underscores),
# we can use a dot instead of brackets and quotes
df.team

a       cubs
b    pirates
c     giants
d    yankees
e    donkeys
Name: team, dtype: object

#### 2.7.3 loc -- row by index

In [ ]:
# to get a row by name, use .loc with the row index
df.loc['a',:]

team             cubs
random       0.315412
fibonacci           2
Name: a, dtype: object

In [ ]:
# for multiple rows, put a list inside the brackets (so two sets of brackets)
df.loc[['a', 'd'],:]

team    random  fibonacci
a     cubs  0.315412          2
d  yankees  0.935132          8

In [ ]:
df.loc[:,'team']

a       cubs
b    pirates
c     giants
d    yankees
e    donkeys
Name: team, dtype: object

In [ ]:
df.loc[:,['team','random']]

team    random
a     cubs  0.315412
b  pirates  0.529036
c   giants  0.351386
d  yankees  0.935132
e  donkeys  0.415327

#### 2.7.4 iloc -- row (or column) by position

In [ ]:
# to get a row by position, use .iloc with the row number
df.iloc[0,:]

team             cubs
random       0.315412
fibonacci           2
Name: a, dtype: object

In [ ]:
# for multiple rows, put a list inside the brackets (so two sets of brackets)
df.iloc[[0, 3],:]

team    random  fibonacci
a     cubs  0.315412          2
d  yankees  0.935132          8

In [ ]:
# or pass a slice
df.iloc[2:,]

team    random  fibonacci
c   giants  0.351386          5
d  yankees  0.935132          8
e  donkeys  0.415327         13

In [ ]:
# iloc also works with columns
df.iloc[:, [0, 2]]

team  fibonacci
a     cubs          2
b  pirates          3
c   giants          5
d  yankees          8
e  donkeys         13

## 3. Exercise



In [ ]:
# Task 1: Import the required packages


In [ ]:
# Task 2: Load data from bank.csv into a DataFrame df


In [ ]:
# Task 3: Show the last 10 transactions of df


In [ ]:
# Task 4:Show the information of df, including the index dtype and column dtypes, non-null values and memory usage.


In [ ]:
# Task 5: Show the transactions where duraiton is lager than 3000
