In [1]:
# For Google Colaboratory
import sys, os
if 'google.colab' in sys.modules:
    # mount google drive
    from google.colab import drive
    drive.mount('/content/gdrive')
    path_to_file = '/content/gdrive/My Drive/Computer_Science_Files/NUS_courses/Applied_Machine_Learning/Applied_ML/Practical' # Please adjust the path accordingly
    os.chdir(path_to_file)
    !pwd

Mounted at /content/gdrive
/content/gdrive/My Drive/Computer_Science_Files/NUS_courses/Applied_Machine_Learning/Applied_ML/Practical


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import svm, datasets
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [3]:
diabetes = pd.read_csv('diabetes.csv')
diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [11]:
X = diabetes.drop(['Outcome'], axis =1)
y = diabetes.Outcome

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=0)

In [6]:
#Scaling the data into a smaller range (-3 to +3)
mean = X_train.mean()
std = X_train.std()

X_train = (X_train - mean) / std
X_test = (X_test - mean) / std

In [7]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='rbf') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC()

In [8]:
print('train acc: ', clf.score(X_train, y_train))
print('test acc: ', clf.score(X_test, y_test))

train acc:  0.8305400372439479
test acc:  0.7575757575757576


In [9]:
# Evaluate Model performance using Test Data
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[139  18]
 [ 38  36]]
              precision    recall  f1-score   support

           0       0.79      0.89      0.83       157
           1       0.67      0.49      0.56        74

    accuracy                           0.76       231
   macro avg       0.73      0.69      0.70       231
weighted avg       0.75      0.76      0.75       231



# Exercise
Try to improve the SVM model performance (e.g. test accuracy) by tuning different hyperparameters, e.g. kernel, C, d, gamma and etc.

In [25]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='rbf', gamma = 4) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(gamma=4)

In [26]:
print('train acc: ', clf.score(X_train, y_train))
print('test acc: ', clf.score(X_test, y_test))



train acc:  1.0
test acc:  0.683982683982684


In [27]:
# Evaluate Model performance using Test Data
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[157   0]
 [ 73   1]]
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       157
           1       1.00      0.01      0.03        74

    accuracy                           0.68       231
   macro avg       0.84      0.51      0.42       231
weighted avg       0.78      0.68      0.56       231



using a high gamma on the rbf kernel, overfits the model on the training data thus producing a 100% accuracy on it, thus unfavourable

In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='rbf', gamma = 1.0) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(gamma=1.0)

In [ ]:
print('train acc: ', clf.score(X_train, y_train))
print('test acc: ', clf.score(X_test, y_test))



train acc:  0.962756052141527
test acc:  0.7402597402597403


In [ ]:
# Evaluate Model performance using Test Data
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[140  17]
 [ 43  31]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.82       157
           1       0.65      0.42      0.51        74

    accuracy                           0.74       231
   macro avg       0.71      0.66      0.67       231
weighted avg       0.73      0.74      0.72       231



using a 'linear' kernel seems to produce more favourable precision and testing accuracy